### ISSUE TITLE
Does not look native on Tumbleweed KDE

### ISSUE THREAD

**Issue by probonopd** [sandman7920/Qt5Demo#1]
`openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180606-Media.iso`:

![](https://user-images.githubusercontent.com/2480569/41757599-9a6c14e4-75d2-11e8-97b4-9e1190ece631.png)

**Comment by sandman7920** [comment]
Try  QT5_DEBUG_RUN=1 ./app.AppImage

**Comment by sandman7920** [comment]
Just tried openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180618-Media.iso

Qt version is 5.11.0

All demos are with 5.10.1

**Comment by probonopd** [comment]
Why was this closed? And what is the solution?

**Comment by sandman7920** [comment]
openSUSE is with latest Qt version 5.11.0
Appimages are with 5.10.1

In order system plugins to be loaded embedded libraries must be >= system

I am working on new Qt5Run version

**Comment by probonopd** [comment]
We need to find a solution that does not need embedded libraries to be >= system, otherwise _all_ existing AppImages will stop to work properly over time when the user updates the system.

**Comment by sandman7920** [comment]
New uploads, build on ubuntu 14.04 with https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.1-trusty.

@probonopd may you test new version, run with QT5_DEBUG_RUN=1

**Comment by probonopd** [comment]
Were you able to solve the _embedded libraries to be >= system_ ?

**Comment by sandman7920** [comment]
Yes if system is with greater version than embeded, `system version` is used with priority
