### ISSUE TITLE
Does not look native on Xubuntu 16.06

### ISSUE THREAD

**Issue by probonopd** [sandman7920/Qt5Demo#2]
`xubuntu-16.04.1-desktop-amd64.iso`:

![notnative](https://user-images.githubusercontent.com/2480569/41784389-11baca70-762f-11e8-9f27-05fc3cbb27e1.png)

**Comment by sandman7920** [comment]
I will investigate.

**Comment by probonopd** [comment]
Why was this closed? Did you find the cause? Thanks.

**Comment by sandman7920** [comment]
Yes on latest build `-platformtheme gtk2` fixes the issue

**Comment by probonopd** [comment]
Thanks. Can we somehow make it not need a command line option? E.g., by using `qt.conf`?

**Comment by sandman7920** [comment]
Yes env QT_QPA_PLATFORMTHEME=gtk2.

From arch
`To automatically set QT_QPA_PLATFORMTHEME for user session, add the following line to ~/.xprofile.`
```bash
[ "$XDG_CURRENT_DESKTOP" = "KDE" ] || [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || export QT_QPA_PLATFORMTHEME="theme"
```

**Comment by sandman7920** [comment]
Qt5run can check `$XDG_CURRENT_DESKTOP` and decide to set GTK2 theme

**Comment by sandman7920** [comment]
it seems that on xubutnu everything is automatically set

```bash
cat X11/Xsession.d/56xubuntu-session
# Set default environment vars in Xubuntu
if [ "$DESKTOP_SESSION" = xubuntu ]; then
    # Disable GTK 3.16 overlay scrollbars
    export GTK_OVERLAY_SCROLLING=0
    # QT5 apps to use GTK style
    export QT_QPA_PLATFORMTHEME=gtk2
    # Workaround clutter issue (LP: #1462445)
    export CLUTTER_BACKEND=x11
fi
```
